# Generated by Django 5.2.4 on 2025-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hazard_images/')),
                ('category', models.CharField(choices=[('road', 'Road'), ('sidewalk', 'Sidewalk'), ('electrical', 'Electrical'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
