name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Django sanity check
        env:
          DEBUG: "False"
          SECRET_KEY: "dummy-ci-secret"
          ALLOWED_HOSTS: "localhost,127.0.0.1"
        run: python backend/manage.py check --deploy

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Use latest npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: |
          set -e
          npm ci || (rm -rf node_modules package-lock.json && npm install)

      - name: Build (skip rollup native binary)
        env:
          ROLLUP_SKIP_NODEJS_NATIVE: '1'
        run: npm run build
